### ISSUE TITLE
Task 2 - Check lại lỗi trong docker compose

### ISSUE THREAD

**Issue by Theodorescsa** [Group-Multi-Projects/EzPDF#7]

**Comment by NhoThoang** [comment]
Ok i got it

**Comment by NhoThoang** [comment]
please refer update you can see update in docker-compose.yml below:
     volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs/web:/app/logs/web
    env_file:

    volumes:
      - ./logs/database:/var/lib/mysql
      - ./logs/database:/var/log/mysql 
      - ./mysql/mysql.cnf:/etc/mysql/mysql.cnf 
    volumes:
      - ./logs/nginx:/var/log/nginx
      you can see all log has been mount ./logs/web, datatabase, nginx and i edit write log in setting.py  
'filename': os.path.join(BASE_DIR, './logs/web/django.log'),
      Can you up date write log in 3 files when log full 3 files you delete file 3nd and move file 1,2 to 2,3 write new in log file 1rd like i said yesterday?

**Comment by Theodorescsa** [comment]
okey
